apiVersion: v1
kind: Service
metadata:
  labels:
    name: bond-web 
    role: service
  name: bond-web-service 
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
      app: bond-web
